<h4>
                        Couleur du CV
                    </h4>
                    <fieldset id="select">
                        <label for="color">Couleur</label>
                        <select name="color" id="color">
                            <option name="bleu" value="blue">Bleu</option>
                            <option name="rouge" value="red">Rouge</option>
                        </select>
                    </fieldset>
                </section>
                <input type="submit" value="Envoyer" />
            </form>
        </main>