
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Routing
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="../assets/styles/css/style.css" />
    </head>
    <body>
        <header>
        </header>
        <main>
           <form action="index.php" method="get">
                <fieldset>
                    <label for="select">Ou voulez-vous aller ?</label>
                    <select name="route" id="select">
                        <option value="">--Choisir une page--</option>
                        <option value="about" name="about">About</option>
                        <option value="contact" name="contact">Contact</option>
                    </select>
                </fieldset>
                <input type="submit" name=""/>
           </form>
           <a href="https://valmontpehautpietri.sites.3wa.io/Cours/php/res03-php-j2/exo2/php/index.php?route=about">About</a>
           <a href="https://valmontpehautpietri.sites.3wa.io/Cours/php/res03-php-j2/exo2/php/index.php?route=contact">Contact</a>
        </main>
    </body>
</html>